name: 3dunet

channels:
  - conda-forge

dependencies:
  - python >=3.11
  - numpy
  - matplotlib
  - nomkl
  - tensorboard
  - tqdm
  - setuptools
  - h5py
  - scipy
  - scikit-image
  - pyyaml
  - pip
  - pip:
    - torch
